### ISSUE TITLE
Fatal error: input file /…/${args.input} does not exist 

### ISSUE THREAD

**Issue by infotexture** [oxygenxml/dita-ot-metrics#6]
With the code on `master` @ b1441d5, the plug-in throws a fatal error when installed in DITA-OT 2.5.4 & run with oXygen 23.1:

    Fatal error: input file /…/${args.input} does not exist 

The problem can be solved by defining a transformation scenario that sets `args.input = ${cf}`.

I'll submit a PR later to make this easier for others.

**Comment by raducoravu** [comment]
Thanks @infotexture , it's useful to have the transformation scenario readily available to be imported.

I consider that the initial problem (the "args.input" not being passed as a parameter) is caused by the fact that Oxygen did not know the metrics report transformation type when running the newly created transformation scenario.
Did you go to the Oxygen Preferences->"DITA-OT" page and configure the DITA-OT 2.5.4 there as a default publishing engine? Or did you edit the newly created transformation scenario and set the "dita.dir" parameter to point to that 2.5.4 DITA OT installation? 
When you added the new plugin in the DITA OT 2.5.4 plugins folder, did you do that from the command line or by running the DITA OT integrator from inside Oxygen? 
Because if you add plugins from the command line to a DITA OT, Oxygen does not know that DITA OT added new transtypes and may need to be restarted to re-scan the entire DITA OT set of installed plugins.
